export default interface AllSourceInfo {
    maxQueue: number;
    //设备资源队列中
    clientQueue: number;
    /// <summary>
    /// 启动设备
    /// </summary>
    startCount: number;
    /// <summary>
    /// 任务数量
    /// </summary>
    jobCount: number;
    /// <summary>
    /// 绑定设备
    /// </summary>
    bindCount: number;
    /// <summary>
    /// 同步设置设备
    /// </summary>
    setingCount: number;
    /// <summary>
    /// 在线设备
    /// </summary>
    onlineCount: number;
    /// <summary>
    /// 离线设备
    /// </summary>
    offlineCount: number;
    /// <summary>
    /// 链接设备
    /// </summary>
    connectCount: number;
    /// <summary>
    /// 充电设备
    /// </summary>
    chargeDeviceCount: number;
    /// <summary>
    /// 充电通道
    /// </summary>
    chargeChannelCount: number;
    /// <summary>
    /// 定时器数量
    /// </summary>
    chTimeTriggerCount: number;
    /// <summary>
    /// 确认上线
    /// </summary>
    affirmOnlineCount: number;
    /// <summary>
    /// 等待结束订单
    /// </summary>
    awaitOrderCount: number;
    /// <summary>
    /// 等待发送订单队列
    /// </summary>
    orderQueueCount: number;
    //通道数量
    channelCount: number;
}